// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using News.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    partial class NewsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("News.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsAgency")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("NewsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("News.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<Guid?>("NewsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Wgt")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("News.Entities.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventUri")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Links")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<double>("Sim")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("News.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DataType")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("LocationValidated")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("News.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<string>("UserRole")
                        .HasColumnType("text");

                    b.Property<string>("UserSurname")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("News.Entities.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<Guid?>("NewsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("News.Entities.View", b =>
                {
                    b.Property<Guid>("ViewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ViewAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ViewId");

                    b.HasIndex("NewsId");

                    b.HasIndex("UserId");

                    b.ToTable("Views");
                });

            modelBuilder.Entity("News.Entities.Author", b =>
                {
                    b.HasOne("News.Entities.News", null)
                        .WithMany("Authors")
                        .HasForeignKey("NewsId");
                });

            modelBuilder.Entity("News.Entities.Category", b =>
                {
                    b.HasOne("News.Entities.News", null)
                        .WithMany("Categories")
                        .HasForeignKey("NewsId");
                });

            modelBuilder.Entity("News.Entities.News", b =>
                {
                    b.HasOne("News.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("News.Entities.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("NewsId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("NewsId");

                            b1.ToTable("News");

                            b1.WithOwner()
                                .HasForeignKey("NewsId");

                            b1.OwnsOne("News.Entities.Country", "Country", b2 =>
                                {
                                    b2.Property<Guid>("LocationNewsId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("LocationNewsId");

                                    b2.ToTable("News");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationNewsId");
                                });

                            b1.Navigation("Country");
                        });

                    b.OwnsOne("News.Entities.Shares", "Shares", b1 =>
                        {
                            b1.Property<Guid>("NewsId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Facebook")
                                .HasColumnType("integer");

                            b1.HasKey("NewsId");

                            b1.ToTable("News");

                            b1.WithOwner()
                                .HasForeignKey("NewsId");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Shares")
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("News.Entities.Source", b =>
                {
                    b.OwnsOne("News.Entities.Ranking", "Ranking", b1 =>
                        {
                            b1.Property<Guid>("SourceId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ImportanceRank")
                                .HasColumnType("integer");

                            b1.HasKey("SourceId");

                            b1.ToTable("Sources");

                            b1.WithOwner()
                                .HasForeignKey("SourceId");
                        });

                    b.OwnsOne("News.Entities.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("SourceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SourceId");

                            b1.ToTable("Sources");

                            b1.WithOwner()
                                .HasForeignKey("SourceId");

                            b1.OwnsOne("News.Entities.Country", "Country", b2 =>
                                {
                                    b2.Property<Guid>("LocationSourceId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("LocationSourceId");

                                    b2.ToTable("Sources");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationSourceId");
                                });

                            b1.Navigation("Country");
                        });

                    b.Navigation("Location");

                    b.Navigation("Ranking");
                });

            modelBuilder.Entity("News.Entities.Video", b =>
                {
                    b.HasOne("News.Entities.News", null)
                        .WithMany("Videos")
                        .HasForeignKey("NewsId");
                });

            modelBuilder.Entity("News.Entities.View", b =>
                {
                    b.HasOne("News.Entities.News", "News")
                        .WithMany("Views")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("News.Entities.User", "Users")
                        .WithMany("Views")
                        .HasForeignKey("UserId");

                    b.Navigation("News");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("News.Entities.News", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("Categories");

                    b.Navigation("Videos");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("News.Entities.User", b =>
                {
                    b.Navigation("Views");
                });
#pragma warning restore 612, 618
        }
    }
}
